workflows:
  build_vue_web:
    name: Build CoinPal Vue App (Tanpa cd web)
    environment:
      node: 18.16.0
      npm: 9.5.1
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build project
        script: npm run build
    artifacts:
      - dist/**
